# (C) Copyright 2024-2026 Anemoi contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from anemoi.transform._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"


from . import units  # noqa: F401  installs the conditional earthkit "(0 - 1)" units work-around
from .data import DataContainer
from .fields import Field
from .fields import FieldList
from .frames import Frame

__all__ = ["DataContainer", "Field", "FieldList", "Frame", "__version__"]
